import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import Header from "../components/Header";
import SettingsSidebar from "../components/SettingsSidebar";
const NotificationSettings = () => {
    const [emailNotifications, setEmailNotifications] = useState(false);
    const [bookingUpdates, setBookingUpdates] = useState(false);
    const [marketing, setMarketing] = useState(false);
    return (_jsxs("div", { className: "flex min-h-screen bg-gray-100 p-10", children: [_jsx(Header, {}), _jsx(SettingsSidebar, {}), _jsxs("div", { className: "flex-1 p-8 mt-8", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "Notifications" }), _jsx("p", { className: "text-gray-600 mb-6", children: "Manage your account settings and preferences." }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Email Notifications" }), _jsx("label", { className: "inline-flex items-center cursor-pointer", children: _jsx("div", { onClick: () => setEmailNotifications(!emailNotifications), className: `relative inline-block w-12 h-6 rounded-full ${emailNotifications ? 'bg-blue-600' : 'bg-gray-300'}`, children: _jsx("span", { className: `absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${emailNotifications ? 'transform translate-x-6' : ''}` }) }) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Booking Updates" }), _jsx("label", { className: "inline-flex items-center cursor-pointer", children: _jsx("div", { onClick: () => setBookingUpdates(!bookingUpdates), className: `relative inline-block w-12 h-6 rounded-full ${bookingUpdates ? 'bg-blue-600' : 'bg-gray-300'}`, children: _jsx("span", { className: `absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${bookingUpdates ? 'transform translate-x-6' : ''}` }) }) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Marketing" }), _jsx("label", { className: "inline-flex items-center cursor-pointer", children: _jsx("div", { onClick: () => setMarketing(!marketing), className: `relative inline-block w-12 h-6 rounded-full ${marketing ? 'bg-blue-600' : 'bg-gray-300'}`, children: _jsx("span", { className: `absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${marketing ? 'transform translate-x-6' : ''}` }) }) })] })] })] })] }));
};
export default NotificationSettings;
